spring:
  application:
    name: rag-poc
# open-ai related configuration
  ai:
    model-name: gpt-3.5-turbo
    temperature: 0.3
    timeout: 60
    logRequests: true
    logResponse: true
    chat-memory: 10
    model:
      name: text-embedding-ada-002


# Quadrant DB related Configuration
  qdrant:
    host: 59f7f28f-640e-4417-a420-5fced5459073.eu-west-2-0.aws.cloud.qdrant.io
    port: 6334
    useTLS: true
    collection-name: testing_modal

# Content Retriever Configuration
  content-retriever:
    max-results: 5
    min-score: 0.4